module.exports = [
  'ACDC',
  'Aerosmith',
  'Alphaville',
  'America',
  'Anthrax',
  'BB King',
  'Black Sabbath',
  'Blondie',
  'Bob Dylan',
  'Bob Marley',
  'Bon Jovi',
  'Breaking Benjamin',
  'Buddy Guy',
  'Buddy Holly',
  'Bullet For My Valentine',
  'Chris Cornell',
  'Cyndi Lauper',
  'David Bowie',
  'Deep Purple',
  'Dire Straits',
  'Dolly Parton',
  'Eagles',
  'Elvis Presley',
  'Epica',
  'Eric Clapton',
  'Eurythmics',
  'Evanescence',
  'Foo Fighters',
  'Green Day',
  'Guns N Roses',
  'Howlin Wolf',
  'In Fear And Faith',
  'Iron Maiden',
  'Janis Joplin',
  'Jimi Hendrix',
  'Johnny Cash',
  'Joni Mitchell',
  'Kansas',
  'Kim Carnes',
  'Lacuna Coil',
  'Led Zeppelin',
  'Linkin Park',
  'Lynyrd Skynyrd',
  'Megadeth',
  'Metallica',
  'Neil Young',
  'Nightwish',
  'Nirvana',
  'Pantera',
  'Papa Roach',
  'Pink Floyd',
  'Queen',
  'Red Hot Chili Peppers',
  'Rush',
  'Scorpions',
  'Skillet',
  'Slayer',
  'Slipknot',
  'Sum 41',
  'System Of A Down',
  'The Beach Boys',
  'The Cranberries',
  'The Doors',
  'The Mamas And The Papas',
  'The Rolling Stones',
  'U2',
  'Van Halen',
  'Willie Nelson',
  'Within Temptation',
]